packages:
  - "."
  - "crates/*"
  - "packages/*"
  - "packages/**/*"
  - "services/*"
  - "apps/*"
  - "e2e/**/*"
  - "e2e/*"
  - "!e2e/wasm"
allowBuilds:
  better-sqlite3: set this to true or false
  esbuild: true
  onnxruntime-node: set this to true or false
  protobufjs: set this to true or false
  sharp: set this to true or false
sharedWorkspaceLockfile: true
autoInstallPeers: true
hoist: true
overrides:
  glob: "10.5.0"
minimumReleaseAge: 0
