//! Shared Rust-owned dense embeddings for native and browser hosts.
//!
//! The backend loads IBM's Granite-Embedding-97M-Multilingual-R2 ModernBERT
//! checkpoint and deliberately keeps model identity beside the loaded model.
//! Callers cannot accidentally persist vectors without the tokenizer, pooling,
//! normalization, and artifact revision that produced them.

use std::sync::Arc;

use candle_core::{DType, Device, IndexOp, Tensor};
use candle_nn::VarBuilder;
use candle_transformers::models::modernbert::{Config as ModernBertConfig, ModernBert};
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};
use thiserror::Error;
use tokenizers::Tokenizer;

const MODEL_ID: &str = "ibm-granite/granite-embedding-97m-multilingual-r2";
const MODEL_REVISION: &str = "835ad14087e140460703cf0fae09f97d469d65c2";
const DIMENSION: usize = 384;

#[derive(Debug, Error)]
pub enum EmbedError {
    #[error("embedding model configuration is invalid: {0}")]
    Config(#[from] serde_json::Error),
    #[error("embedding tokenizer could not be loaded: {0}")]
    Tokenizer(String),
    #[error("embedding tensor operation failed: {0}")]
    Tensor(String),
    #[error("embedding model file operation failed: {0}")]
    Io(#[from] std::io::Error),
    #[error("embedding output has dimension {got}, expected {expected}")]
    Dimension { got: usize, expected: usize },
    #[error("embedding output contains non-finite values")]
    NonFinite,
    #[error("embedding input is empty")]
    EmptyInput,
}

pub type Result<T> = std::result::Result<T, EmbedError>;

/// Immutable identity of the vector space generated by [`GraniteEmbedder`].
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct EmbedderIdentity {
    pub model: String,
    pub revision: String,
    pub artifact_sha256: String,
    pub tokenizer_sha256: String,
    pub config_sha256: String,
    pub source_dtype: String,
    pub runtime_dtype: String,
    pub pooling: String,
    pub normalize: bool,
    pub dimension: usize,
}

impl EmbedderIdentity {
    fn from_bytes(weights: &[u8], tokenizer: &[u8], config: &[u8]) -> Self {
        Self {
            model: MODEL_ID.to_string(),
            revision: MODEL_REVISION.to_string(),
            artifact_sha256: digest(weights),
            tokenizer_sha256: digest(tokenizer),
            config_sha256: digest(config),
            source_dtype: "bf16".to_string(),
            runtime_dtype: "f32".to_string(),
            pooling: "cls".to_string(),
            normalize: true,
            dimension: DIMENSION,
        }
    }
}

fn digest(bytes: &[u8]) -> String {
    let mut hasher = Sha256::new();
    hasher.update(bytes);
    let hex = hasher
        .finalize()
        .iter()
        .map(|byte| format!("{byte:02x}"))
        .collect::<String>();
    format!("sha256:{hex}")
}

/// Loaded Granite embedding model. The model is immutable and safe to share
/// between host adapters; inference itself is deterministic and side-effect free.
pub struct GraniteEmbedder {
    model: ModernBert,
    tokenizer: Arc<Tokenizer>,
    config: ModernBertConfig,
    identity: EmbedderIdentity,
    device: Device,
}

impl std::fmt::Debug for GraniteEmbedder {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("GraniteEmbedder").field("identity", &self.identity).finish_non_exhaustive()
    }
}

impl GraniteEmbedder {
    /// Load a Granite checkpoint from bytes. This is the native and WASM-safe
    /// entry point; hosts own downloading, caching, and checksum verification.
    pub fn from_safetensors_bytes(weights: &[u8], tokenizer_json: &[u8], config_json: &[u8]) -> Result<Self> {
        let config: ModernBertConfig = serde_json::from_slice(config_json)?;
        if config.hidden_size != DIMENSION {
            return Err(EmbedError::Dimension { got: config.hidden_size, expected: DIMENSION });
        }
        let tokenizer = Tokenizer::from_bytes(tokenizer_json).map_err(|e| EmbedError::Tokenizer(e.to_string()))?;
        let device = Device::Cpu;
        // Granite publishes ModernBERT weights without the `model.` prefix used
        // by Candle's generic ModernBert loader. The renamer keeps the upstream
        // implementation reusable without mutating the artifact on disk.
        let vb = VarBuilder::from_buffered_safetensors(weights.to_vec(), DType::F32, &device)
            .map_err(|e| EmbedError::Tensor(e.to_string()))?
            .rename_f(|name| format!("model.{name}"));
        let model = ModernBert::load(vb, &config).map_err(|e| EmbedError::Tensor(e.to_string()))?;
        Ok(Self {
            model,
            tokenizer: Arc::new(tokenizer),
            identity: EmbedderIdentity::from_bytes(weights, tokenizer_json, config_json),
            config,
            device,
        })
    }

    /// Load a checkpoint directory on native hosts.
    #[cfg(not(target_arch = "wasm32"))]
    pub fn from_files(weights: impl AsRef<std::path::Path>, tokenizer: impl AsRef<std::path::Path>, config: impl AsRef<std::path::Path>) -> Result<Self> {
        Self::from_safetensors_bytes(
            &std::fs::read(weights)?,
            &std::fs::read(tokenizer)?,
            &std::fs::read(config)?,
        )
    }

    pub fn identity(&self) -> &EmbedderIdentity {
        &self.identity
    }

    pub fn dimension(&self) -> usize {
        self.identity.dimension
    }

    /// Embed documents and queries with the same model contract. Granite R2
    /// uses CLS pooling for both sides and does not require an instruction
    /// prefix; query/document distinction remains explicit at the API boundary.
    pub fn embed_documents(&self, texts: &[String]) -> Result<Vec<Vec<f32>>> {
        texts.iter().map(|text| self.embed_one(text)).collect()
    }

    pub fn embed_query(&self, text: &str) -> Result<Vec<f32>> {
        self.embed_one(text)
    }

    fn embed_one(&self, text: &str) -> Result<Vec<f32>> {
        if text.trim().is_empty() {
            return Err(EmbedError::EmptyInput);
        }
        let encoding = self
            .tokenizer
            .encode(text, true)
            .map_err(|e| EmbedError::Tokenizer(e.to_string()))?;
        let mut ids = encoding.get_ids().to_vec();
        let mut mask = encoding.get_attention_mask().to_vec();
        let max_len = self.config.max_position_embeddings;
        ids.truncate(max_len);
        mask.truncate(max_len);
        if ids.is_empty() {
            return Err(EmbedError::EmptyInput);
        }
        let ids = Tensor::new(ids.as_slice(), &self.device)
            .map_err(|e| EmbedError::Tensor(e.to_string()))?
            .unsqueeze(0)
            .map_err(|e| EmbedError::Tensor(e.to_string()))?;
        let mask = Tensor::new(mask.as_slice(), &self.device)
            .map_err(|e| EmbedError::Tensor(e.to_string()))?
            .unsqueeze(0)
            .map_err(|e| EmbedError::Tensor(e.to_string()))?;
        let hidden = self.model.forward(&ids, &mask).map_err(|e| EmbedError::Tensor(e.to_string()))?;
        let vector = hidden
            .i((0, 0))
            .map_err(|e| EmbedError::Tensor(e.to_string()))?
            .to_vec1::<f32>()
            .map_err(|e| EmbedError::Tensor(e.to_string()))?;
        if vector.len() != DIMENSION {
            return Err(EmbedError::Dimension { got: vector.len(), expected: DIMENSION });
        }
        let norm = vector.iter().map(|value| value * value).sum::<f32>().sqrt();
        let norm = if norm > 0.0 { norm } else { 1.0 };
        let vector: Vec<f32> = vector.into_iter().map(|value| value / norm).collect();
        if vector.iter().any(|value| !value.is_finite()) {
            return Err(EmbedError::NonFinite);
        }
        Ok(vector)
    }
}

#[cfg(test)]
mod tests {
    use super::{EmbedderIdentity, DIMENSION};

    #[test]
    fn identity_is_serializable_and_explicit() {
        let identity = EmbedderIdentity {
            model: "test".into(),
            revision: "rev".into(),
            artifact_sha256: "sha256:a".into(),
            tokenizer_sha256: "sha256:b".into(),
            config_sha256: "sha256:c".into(),
            source_dtype: "bf16".into(),
            runtime_dtype: "f32".into(),
            pooling: "cls".into(),
            normalize: true,
            dimension: DIMENSION,
        };
        let json = serde_json::to_string(&identity).unwrap();
        assert_eq!(serde_json::from_str::<EmbedderIdentity>(&json).unwrap(), identity);
    }
}
