export {
  ingestFolder,
  extractDocumentForUi as extractDocument,
  queryRagForUi as queryRag,
  redactDocumentForUi as redactDocument,
  rehydrateSpanForUi,
  reviewAndRepush,
  chunkIndexFromToken,
  warmupModels,
  type ExtractedDocument,
  type IngestResult,
  type IngestProgress,
  type IngestContext,
  type WarmupProgress,
  type WarmupResult,
  type ReviewContext,
  type ReviewDecision,
  type ReviewResult,
} from "./adapter";
export { openVault, rehydrate, listPiiTypes, type RedactionEntry } from "@xberg-io/wasm-pipeline-real";
